rvm:
  - 2.1
  - 2.2
  - 2.3.1

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

sudo: false

language: ruby
cache: bundler

addons:
  postgresql: "9.4"

before_script:
  - psql -c "CREATE DATABASE eaco;" -U postgres

script: bundle exec rake EACO_AR_CONFIG=./features/active_record.travis.yml
