rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0

gemfile:
#  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE eaco;" -U postgres

script: bundle exec rake EACO_AR_CONFIG=./features/active_record.travis.yml
